### ISSUE TITLE
Problems with module killing the Hoobs bridge service

### ISSUE THREAD

**Issue by jpop77** [andreseko/homebridge-braava-m6#2]
Have you run into an error like this before.  Background - Running Hoobs latest edition on macOS.  I ran the utility and was successful at pulling the ID and PW required.  Added those credentials and once saved, the bridge remains down.  Here is what I see in the logs:

Here is where I see the plugin being registered prior to the failure:
10/29/2020, 8:15:32 PM Loaded plugin 'homebridge-braava-m6'
10/29/2020, 8:15:32 PM [10/29/2020, 8:15:32 PM] Registering platform 'homebridge-braava-m6.Braava'

Here is what I am seeing in the logs:

Error loading platform requested in your config.json at position 4
10/29/2020, 8:15:32 PM Error: The requested platform 'Braava M6' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Keep me posted if you have any suggestions on what I am missing here that is causing this to fail.

**Comment by andreseko** [comment]
Thank you for your report.
I've update the configuration file.

`"platforms": [
    {
      "platform": "Braava",
      "name": "Braava",
      "robots": [
        {
          "name": "Braava M6",
          "blid":"123456789abcdefg",
          "password": ":1:2345678901:ABCDEFGHIJKLMNOP",
          "address": "192.168.x.xx"
        }
      ]
    }
  ]`
